#pragma once
#define WINDOW_WIDTH 1000
#define WINDOW_HEIGHT 1000
#define WINDOW_TITLE "Mazer GUI"
#define MAZE_WIDTH 10
#define MAZE_HEIGHT 10
#define DEFAULT_DELAY 300
#define DEFAULT_ZOOM 2.0f
#define RAYCAST_WIDTH 1